import React from 'react';
import { jsPDF } from 'jspdf';

const ResultSummary = ({ score, totalQuestions, userInfo, answers, questions }) => {
  const percentage = ((score / totalQuestions) * 100).toFixed(0);
  
  const getFeedback = () => {
    if (percentage >= 90) return {
      title: "Exceptional Excellence",
      msg: "You have demonstrated complete mastery of the KIN Training modules. Outstanding performance!",
      color: "var(--success)"
    };
    if (percentage >= 75) return {
      title: "Strong Performance",
      msg: "Great job! You have a solid grasp of the core values and procedures of KidsInspiring Nation.",
      color: "var(--primary-color)"
    };
    if (percentage >= 50) return {
      title: "Good Foundation",
      msg: "You've passed the assessment, but there are areas for improvement. Review your incorrect answers.",
      color: "#f59e0b"
    };
    return {
      title: "Learning Opportunity",
      msg: "There is still much to learn. We encourage you to study the KIN principles further and retake the test.",
      color: "var(--error)"
    };
  };

  const feedback = getFeedback();

  const categoryScores = questions.reduce((acc, q) => {
    const cat = q.category || 'General';
    if (!acc[cat]) acc[cat] = { correct: 0, total: 0 };
    acc[cat].total++;
    if (answers[q.id] === q.answer) acc[cat].correct++;
    return acc;
  }, {});

  const downloadPDFReport = () => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(37, 99, 235);
    doc.text('KIN Assessment Report', 20, 30);
    
    doc.setFontSize(14);
    doc.setTextColor(100);
    doc.text(`Candidate: ${userInfo.name}`, 20, 45);
    doc.text(`Date: ${date}`, 20, 52);
    doc.text(`Final Score: ${score} / ${totalQuestions} (${percentage}%)`, 20, 59);
    
    // Category Breakdown
    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235);
    doc.text('Performance by Area', 20, 75);
    
    let y = 85;
    Object.entries(categoryScores).forEach(([cat, stats]) => {
      const perc = ((stats.correct / stats.total) * 100).toFixed(0);
      doc.setFontSize(12);
      doc.setTextColor(50);
      doc.text(`${cat}: ${perc}% (${stats.correct}/${stats.total} correct)`, 25, y);
      y += 10;
    });
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text('Generated by KIN Nation-Builder Tool', 20, 280);
    
    doc.save(`KIN_Report_${userInfo.name.replace(/\s+/g, '_')}.pdf`);
  };

  const downloadCertificate = () => {
    if (percentage < 80) {
      alert("Certificates are awarded for scores of 80% and above. Keep studying!");
      return;
    }
    
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4'
    });
    
    // Border
    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(2);
    doc.rect(10, 10, 277, 190);
    
    // Content
    doc.setFontSize(40);
    doc.setTextColor(37, 99, 235);
    doc.text('CERTIFICATE OF EXCELLENCE', 148, 60, { align: 'center' });
    
    doc.setFontSize(20);
    doc.setTextColor(100);
    doc.text('This is to certify that', 148, 85, { align: 'center' });
    
    doc.setFontSize(32);
    doc.setTextColor(0);
    doc.text(userInfo.name.toUpperCase(), 148, 105, { align: 'center' });
    
    doc.setFontSize(18);
    doc.setTextColor(100);
    doc.text('has successfully completed the', 148, 125, { align: 'center' });
    doc.text('KIN Nation Builders Training Assessment', 148, 135, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235);
    doc.text(`Score: ${percentage}% excellence`, 148, 155, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(150);
    doc.text(`Issued on ${new Date().toLocaleDateString()}`, 148, 180, { align: 'center' });
    
    doc.save(`KIN_Certificate_${userInfo.name.replace(/\s+/g, '_')}.pdf`);
  };

  return (
    <div className="container result-container glass fade-in">
      <div className="result-header">
        <h1>Assessment Results</h1>
        <p>{userInfo.name} • Class of {userInfo.yearJoined}</p>
      </div>

      <div className="score-summary">
        <div className="score-viz" style={{'--score-color': feedback.color}}>
          <div className="score-inner">
            <span className="score-num">{score}</span>
            <span className="score-denom">/ {totalQuestions}</span>
          </div>
          <svg className="score-svg">
             <circle className="bg" cx="80" cy="80" r="70"></circle>
             <circle className="meter" cx="80" cy="80" r="70" style={{strokeDashoffset: 440 - (440 * (score / totalQuestions))}}></circle>
          </svg>
        </div>
        <div className="score-info">
          <h2 style={{color: feedback.color}}>{feedback.title}</h2>
          <p>{feedback.msg}</p>
          <div className="action-buttons mt-1">
            <button onClick={downloadPDFReport} className="btn primary-btn">
               Download Report (PDF)
            </button>
            {percentage >= 80 && (
              <button onClick={downloadCertificate} className="btn success-btn">
                 Download Certificate
              </button>
            )}
            <button onClick={() => window.location.reload()} className="btn secondary-btn">
               Retake
            </button>
          </div>
        </div>
      </div>

      <div className="category-breakdown glass">
        <h3>Performance by Area</h3>
        <div className="category-grid">
          {Object.entries(categoryScores).map(([cat, stats]) => {
            const perc = ((stats.correct / stats.total) * 100).toFixed(0);
            return (
              <div key={cat} className="category-item">
                <div className="cat-info">
                  <span className="cat-name">{cat}</span>
                  <span className="cat-perc">{perc}%</span>
                </div>
                <div className="cat-bar-bg">
                  <div className="cat-bar-fill" style={{ width: `${perc}%` }}></div>
                </div>
                <span className="cat-count">{stats.correct}/{stats.total} correct</span>
              </div>
            );
          })}
        </div>
      </div>

      <div className="review-area">
        <h3>Detailed Review</h3>
        <div className="review-list">
          {questions.map((q, idx) => {
            const isCorrect = answers[q.id] === q.answer;
            return (
              <div key={q.id} className={`review-card-modern ${isCorrect ? 'correct' : 'incorrect'}`}>
                <div className="r-header">
                  <span className="r-num">Q{idx + 1}</span>
                  <span className={`r-status-icon`}>{isCorrect ? '✓' : '✗'}</span>
                </div>
                <p className="r-question">{q.text}</p>
                <div className="r-answer-comparison">
                  <div className="r-user">
                    <small>Your Answer</small>
                    <p>{answers[q.id] ? `${answers[q.id]}) ${q.options[answers[q.id]]}` : 'Not Answered'}</p>
                  </div>
                  {!isCorrect && (
                    <div className="r-correct">
                      <small>Correct Answer</small>
                      <p>{q.answer}) {q.options[q.answer]}</p>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default ResultSummary;
